# Overview (Machine Learning & Deep Learning)

<img src="https://blogs.nvidia.com/wp-content/uploads/2016/07/Deep_Learning_Icons_R5_PNG.jpg.png" cat[tion="from NDIVIA Blog">

- 인공지능(Artificial Intelligence) : 기계로 구현한 인간 지능

- 기계학습(Machine Learning) : 인공지능을 구현한 방법들

- 딥러닝(Deep Learning) : 기계학습을 구현한 한 기법

### Deep Learning 등장 배경

- Algorithm 개선 
      - Deep NN 에서의 vanishing gradient 해결 : CNN, RNN etc.
- GPU
- Big Data


### Deep Learning 의 활용분야

- 영상인식 및 묘사

- 

### Deep Learning 프레임워크

- **Numpy** : linear algebra libraries

- **TensorFlow** (from Google): automatic gradient calculation

- **Pytorch** (from facebook): automatic gradient calculation
 - Imperative: Python first / intuitive / Easy to use
 - GPU acceleration
 - Linux/OSX
 


### Example using Numpy

$$ \text{output} = x*y + z $$

In [2]:
import numpy as np
from datetime import datetime
start = datetime.now()

np.random.seed(0)

N,D = 3,4

x = np.random.randn(N,D)
y = np.random.randn(N,D)
z = np.random.randn(N,D)

a = x * y
b = a + z
c = np.sum(b)

grad_c = 1.0
grad_b = grad_c * np.ones((N,D))
grad_a = grad_b.copy()
grad_z = grad_b.copy()
grad_y = grad_a * y
grad_x = grad_a * x

print(grad_x)
print(grad_y)
print(grad_z)
print(datetime.now()-start)

[[ 1.76405235  0.40015721  0.97873798  2.2408932 ]
 [ 1.86755799 -0.97727788  0.95008842 -0.15135721]
 [-0.10321885  0.4105985   0.14404357  1.45427351]]
[[ 0.76103773  0.12167502  0.44386323  0.33367433]
 [ 1.49407907 -0.20515826  0.3130677  -0.85409574]
 [-2.55298982  0.6536186   0.8644362  -0.74216502]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
0:00:00.000997


In [ ]:
import tensorflow as tf
import numpy as np
from datetime import datetime
start = datetime.now()

with tf.device('/gpu:0'):
    x = tf.placeholder(tf.float32)
    y = tf.placeholder(tf.float32)
    z = tf.placeholder(tf.float32)

    a = x * y
    b = a + z
    c = tf.reduce_sum(b)
    
grad_x, grad_y, grad_z = tf.gradients(c,[x,y,z])

with tf.Session() as sess:
    values = {
        x: np.random.randn(N,D),
        y: np.random.randn(N,D),
        z: np.random.randn(N,D)           
    }
    out = sess.run([c,grad_x,grad_y,grad_z],feed_dict = values)
    c_val, grad_x_val, grad_y_val, grad_z_val = out

print(grad_x_val)
print(grad_y_val)
print(grad_z_val)
print(datetime.now()-start)


In [7]:
import torch
from torch.autograd import Variable
from datetime import datetime
start = datetime.now()

N,D = 3,4

#x = Variable(torch.randn(N,D).cuda(),requires_grad=True)
#y = Variable(torch.randn(N,D).cuda(),requires_grad=True)
#z = Variable(torch.randn(N,D).cuda(),requires_grad=True)
x = Variable(torch.randn(N,D),requires_grad=True)
y = Variable(torch.randn(N,D),requires_grad=True)
z = Variable(torch.randn(N,D),requires_grad=True)

a = x * y
b = a + z
c = torch.sum(b)

#c.backward(gradient=torch.cuda.FloatTensor([1.0]))
c.backward(gradient=torch.FloatTensor([1.0]))

print(x.grad)
print(y.grad)
print(z.grad)
print(datetime.now()-start)

RuntimeError: invalid gradient at index 0 - expected shape [] but got [1]